<!DOCTYPE html>
<html ng-app="easyapp">
    <head>
        <title page-title></title>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel="shortcut icon" href="assets/img/logo.ico" type="image/x-icon">
        <link href="bower_components/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet">
        <link href="bower_components/angular-loading-bar/loading-bar.min.css" rel="stylesheet">
        <!-- Font awesome -->
        <link href="assets/font-awesome/css/font-awesome.css" rel="stylesheet">
        <link href="assets/css/animate.css" rel="stylesheet">
        <link id="loadBefore" href="assets/css/style.css" rel="stylesheet">
    </head>
    <body ng-controller="MainCtrl as main" class="{{$state.current.data.specialClass}}" landing-scrollspy id="page-top">
        <div ui-view></div>
        <script src="bower_components/jquery/dist/jquery.min.js"></script>
        <script src="bower_components/bootstrap/dist/js/bootstrap.min.js"></script>
        <script src="assets/js/scripts.js"></script>
        <!-- MetsiMenu -->
        <script src="bower_components/metisMenu/jquery.metisMenu.js"></script>
        <!-- SlimScroll -->
        <script src="bower_components/slimscroll/jquery.slimscroll.min.js"></script>
        <!-- Peace JS -->
        <script src="bower_components/pace/pace.min.js"></script>
        <!-- Custom and plugin javascript -->
        <script src="assets/js/inspinia.js"></script>
        <!-- Main Angular scripts-->
        <script src="bower_components/angular/angular.min.js"></script>
        <script src="bower_components/angular/angular-sanitize.min.js"></script>
        <script src="bower_components/oclazyload/dist/ocLazyLoad.min.js"></script>
        <script src="bower_components/angular-translate/angular-translate.min.js"></script>
        <script src="bower_components/ui-router/angular-ui-router.min.js"></script>
        <script src="bower_components/angular/ui-bootstrap-tpls-1.1.2.min.js"></script>
        <script src="bower_components/angular-idle/angular-idle.js"></script>
        <script src="bower_components/angular-loading-bar/loading-bar.min.js"></script>
        <script src="bower_components/angular-images-resizer/angular-images-resizer.js"></script>
        <script src="assets/mvc/app.js"></script>
        <script src="assets/mvc/config.js"></script>
        <script src="assets/mvc/directives.js"></script>
        <script src="assets/mvc/controllers.js"></script>
        <script src="assets/mvc/controllers/ArticulosCtrl.js"></script>
        <script src="assets/mvc/controllers/GaleriaCtrl.js"></script>
        <script src="assets/mvc/translations.js"></script>
        <script>
                $(function () {
                    $(window).bind("load resize", function () {
                        if ($(document).width() < 769) {
                            $('body').addClass('body-small')
                        } else {
                            $('body').removeClass('body-small')
                        }
                    });
                    function fix_height() {
                        var heightWithoutNavbar = $("body > #wrapper").height() - 61;
                        $(".sidebard-panel").css("min-height", heightWithoutNavbar + "px");

                        var navbarHeigh = $('nav.navbar-default').height();
                        var wrapperHeigh = $('#page-wrapper').height();

                        if (navbarHeigh > wrapperHeigh) {
                            $('#page-wrapper').css("min-height", navbarHeigh + "px");
                        }

                        if (navbarHeigh < wrapperHeigh) {
                            $('#page-wrapper').css("min-height", $(window).height() + "px");
                        }

                        if ($('body').hasClass('fixed-nav')) {
                            if (navbarHeigh > wrapperHeigh) {
                                $('#page-wrapper').css("min-height", navbarHeigh - 60 + "px");
                            } else {
                                $('#page-wrapper').css("min-height", $(window).height() - 60 + "px");
                            }
                        }

                    }


                    $(window).bind("load resize scroll", function () {
                        if (!$("body").hasClass('body-small')) {
                            fix_height();
                        }
                    });

                    // Move right sidebar top after scroll
                    $(window).scroll(function () {
                        if ($(window).scrollTop() > 0 && !$('body').hasClass('fixed-nav')) {
                            $('#right-sidebar').addClass('sidebar-top');
                        } else {
                            $('#right-sidebar').removeClass('sidebar-top');
                        }
                    });


                    setTimeout(function () {
                        fix_height();
                    })
                });
        </script>
    </body>
</html>
