<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<div class="page-header">
    <h1>
        Search gd_grupo
    </h1>
    <p>
        <?php echo $this->tag->linkTo(array("gd_grupo/new", "Create gd_grupo")) ?>
    </p>
</div>

<?php echo $this->getContent() ?>

<?php
    echo $this->tag->form(
        array(
            "gd_grupo/search",
            "autocomplete" => "off",
            "class" => "form-horizontal"
        )
    );
?>

<div class="form-group">
    <label for="fieldGrupoId" class="col-sm-2 control-label">Grupo</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("grupo_id", "type" => "number", "class" => "form-control", "id" => "fieldGrupoId")) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldGrupoNombre" class="col-sm-2 control-label">Grupo Of Nombre</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("grupo_nombre", "size" => 30, "class" => "form-control", "id" => "fieldGrupoNombre")) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldGrupoEstado" class="col-sm-2 control-label">Grupo Of Estado</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("grupo_estado", "type" => "number", "class" => "form-control", "id" => "fieldGrupoEstado")) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldGrupoFecha" class="col-sm-2 control-label">Grupo Of Fecha</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("grupo_fecha", "size" => 30, "class" => "form-control", "id" => "fieldGrupoFecha")) ?>
    </div>
</div>


<div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
        <?php echo $this->tag->submitButton(array("Search", "class" => "btn btn-default")) ?>
    </div>
</div>

<?php echo $this->tag->endForm(); ?>
